In [1]:
import pandas as pd
import numpy as np

In [3]:
infra = pd.read_csv('광주광역시_종합생활인프라현황_5179.csv', encoding='euc-kr')

In [4]:
infra

,EMD_CD,EMD_NM,SGG_OID,COL_ADM_SE,GID,전통시장,공연시설,노인요양병원,대규모점포,도서관,미술관,박물관,의료시설,주민센터,체육시설,종합생활인프라
0,29170129,연제동,1430,29170,5666,0,0,0,0,3,0,0,0,0,3,6
1,29170109,운암동,1431,29170,5667,1,2,1,0,13,1,0,13,3,3,37
2,29200176,덕림동,1556,29200,5661,0,0,1,0,0,0,0,0,0,1,2
3,29200160,삼거동,1560,29200,5662,0,0,3,0,0,0,0,3,0,1,7
4,29170108,동림동,1429,29170,5665,0,0,1,0,6,0,0,3,1,6,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,29140115,광천동,114,29140,3405,0,0,1,1,3,0,0,4,1,2,12
198,29140118,쌍촌동,112,29140,3407,0,3,1,0,14,0,0,8,2,10,38
199,29140121,내방동,131,29140,3408,0,0,0,0,1,0,0,0,0,1,2
200,29140117,덕흥동,97,29140,3411,0,0,1,0,0,0,0,0,0,5,6
201,29110105,대의동,168,29110,3412,0,0,0,0,0,1,1,0,0,0,2

In [11]:
# 충장로 / 금남로에 해당하는 주소 조회
infra[infra['EMD_NM'].str.contains('충장|금남')]

,EMD_CD,EMD_NM,SGG_OID,COL_ADM_SE,GID,전통시장,공연시설,노인요양병원,대규모점포,도서관,미술관,박물관,의료시설,주민센터,체육시설,종합생활인프라
22,29110133,금남로3가,166,29110,3413,0,0,0,0,1,1,0,0,0,0,2
23,29110132,금남로2가,165,29110,3414,0,0,0,0,2,0,0,0,0,0,2
24,29110131,금남로1가,164,29110,3415,0,0,0,0,0,0,0,0,0,0,0
25,29110130,충장로4가,163,29110,3416,0,0,0,1,0,0,0,0,1,0,2
26,29110129,충장로3가,162,29110,3417,0,0,0,1,0,0,0,0,0,0,1
27,29110128,충장로2가,161,29110,3418,0,0,0,0,0,0,0,0,0,0,0
28,29110127,충장로1가,160,29110,3419,0,0,0,0,0,0,0,0,0,0,0
39,29110102,금남로5가,145,29110,3434,0,0,0,0,1,0,0,0,0,0,1
47,29110103,충장로5가,170,29110,3444,0,0,0,0,0,0,0,0,0,0,0
48,29110134,금남로4가,169,29110,3445,0,0,0,0,0,0,0,0,0,0,0

In [12]:
trade = pd.read_csv('당근마켓_전동휠체어_거래기록.csv', encoding='euc-kr')

In [16]:
trade.index.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141],
      dtype=int64)

In [17]:
trade.columns.values

array(['Unnamed: 0', '거래 장소'], dtype=object)

In [20]:
trade = trade.drop(['Unnamed: 0'], axis=1)

In [33]:
used = trade

In [35]:
# 중고거래 플랫폼 웹 크롤링 결과 df
## 법정동과 일치하지 않는 분할된 행정동만 조회
used[used['거래 장소'].str.contains('1|2|3')].drop_duplicates()

           거래 장소
11    광주 북구 두암2동
12    광주 북구 오치2동
13    광주 남구 백운1동
34    광주 서구 농성1동
38    광주 서구 화정1동
54    광주 남구 봉선1동
59    광주 서구 금호1동
60   광주 광산구 송정2동
63    광주 북구 운암3동
65    광주 서구 농성2동
88    광주 동구 산수1동
102   광주 남구 봉선2동
107  광주 광산구 첨단1동
108   광주 북구 운암1동
112   광주 북구 오치1동

In [36]:
import re

In [71]:
addr = list(used['거래 장소'][used['거래 장소'].str.contains('1|2|3')].drop_duplicates())

In [83]:
# 행정동을 법정동으로 변경하는 함수
def get_final_list(addr:list):
    addr_list = []
    for i in addr_:
        if '첨단' in i:      # 첨단1동은 법정동상 월계동이므로 추가적인 변환 필요 
            i = re.sub('첨단', '월계', i)     
        result = re.sub('1|2|3', '', i)
        addr_list.append(result)
    final = pd.DataFrame(addr_list, columns=['거래 장소'])
    final_list = final.drop_duplicates()
    return final_list

In [84]:
get_final_list(addr)

         거래 장소
0    광주 북구 두암동
1    광주 북구 오치동
2    광주 남구 백운동
3    광주 서구 농성동
4    광주 서구 화정동
5    광주 남구 봉선동
6    광주 서구 금호동
7   광주 광산구 송정동
8    광주 북구 운암동
10   광주 동구 산수동
12  광주 광산구 월계동

In [92]:
data = pd.read_csv('수요분석결과_운암동_temp.csv', index_col='ID')

In [94]:
data

,광주 북구 북문대로 168,광주 북구 서강로 160-1,광주 북구 금호로40번길 9,광주 북구 운암동 497,광주 북구 서강로 155,광주 북구 서강로54번길 11,광주 북구 운암동 69-5,광주 북구 서강로54번길 10,광주 북구 운암동 1040-14,광주 북구 운암동 99,광주 북구 운암동 319,광주 북구 운암동 68-2
ID,,,,,,,,,,,,
광주 북구 북문대로 168,0.000000,490.134700,1936.537991,1635.886550,345.374760,738.770457,1059.403185,864.957940,277.488541,1230.286798,560.210521,1083.594256
광주 북구 서강로 160-1,490.134700,0.000000,1608.623599,1349.449544,173.517454,985.372567,946.879248,1060.630794,507.374614,1049.646019,402.771959,1072.414484
광주 북구 금호로40번길 9,1936.537991,1608.623599,0.000000,332.314996,1765.189198,1723.937301,1020.477900,1633.795368,1716.440393,811.925575,1376.865626,1189.047924
광주 북구 운암동 497,1635.886550,1349.449544,332.314996,0.000000,1495.006899,1391.653385,688.273018,1302.171430,1403.538849,479.611186,1076.448759,860.095627
광주 북구 서강로 155,345.374760,173.517454,1765.189198,1495.006899,0.000000,951.741626,1035.941013,1047.493381,445.496449,1162.292921,476.535096,1131.219713
광주 북구 서강로54번길 11,738.770457,985.372567,1723.937301,1391.653385,951.741626,0.000000,703.557389,147.876948,509.013940,912.101506,670.636099,567.839461
광주 북구 운암동 69-5,1059.403185,946.879248,1020.477900,688.273018,1035.941013,703.557389,0.000000,621.678244,792.942247,209.319422,559.406232,229.939957
광주 북구 서강로54번길 10,864.957940,1060.630794,1633.795368,1302.171430,1047.493381,147.876948,621.678244,0.000000,616.420972,824.677895,709.390322,453.430853
광주 북구 운암동 1040-14,277.488541,507.374614,1716.440393,1403.538849,445.496449,509.013940,792.942247,616.420972,0.000000,974.230487,359.954650,806.271675
광주 북구 운암동 99,1230.286798,1049.646019,811.925575,479.611186,1162.292921,912.101506,209.319422,824.677895,974.230487,0.000000,695.138318,395.817552
광주 북구 운암동 319,560.210521,402.771959,1376.865626,1076.448759,476.535096,670.636099,559.406232,709.390322,359.954650,695.138318,0.000000,669.762880
광주 북구 운암동 68-2,1083.594256,1072.414484,1189.047924,860.095627,1131.219713,567.839461,229.939957,453.430853,806.271675,395.817552,669.762880,0.000000

In [90]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 12 non-null     object
 1   광주 북구 북문대로 168     12 non-null     float64
 2   광주 북구 서강로 160-1    12 non-null     float64
 3   광주 북구 금호로40번길 9    12 non-null     float64
 4   광주 북구 운암동 497      12 non-null     float64
 5   광주 북구 서강로 155      12 non-null     float64
 6   광주 북구 서강로54번길 11   12 non-null     float64
 7   광주 북구 운암동 69-5     12 non-null     float64
 8   광주 북구 서강로54번길 10   12 non-null     float64
 9   광주 북구 운암동 1040-14  12 non-null     float64
 10  광주 북구 운암동 99       12 non-null     float64
 11  광주 북구 운암동 319      12 non-null     float64
 12  광주 북구 운암동 68-2     12 non-null     float64
dtypes: float64(12), object(1)
memory usage: 1.3+ KB

In [91]:
data.describe()

,광주 북구 북문대로 168,광주 북구 서강로 160-1,광주 북구 금호로40번길 9,광주 북구 운암동 497,광주 북구 서강로 155,광주 북구 서강로54번길 11,광주 북구 운암동 69-5,광주 북구 서강로54번길 10,광주 북구 운암동 1040-14,광주 북구 운암동 99,광주 북구 운암동 319,광주 북구 운암동 68-2
count,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,851.887142,803.901249,1259.596323,1001.204187,835.817376,775.208390,655.651488,773.543679,700.764401,728.753973,629.760039,704.952865
std,569.861745,485.039699,612.208196,523.816745,543.524381,476.723168,352.715980,460.443087,481.732646,384.636813,347.165781,384.972935
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,453.944715,468.294014,968.339819,636.107560,420.466027,553.133080,477.039664,575.673443,424.110999,458.662777,458.094312,439.027528
50%,801.864198,966.125908,1492.744612,1189.310095,993.841320,721.163923,695.915204,767.034108,562.717456,818.301735,614.986700,738.017277
75%,1120.267391,1063.576717,1718.314620,1394.624751,1138.988015,960.149362,965.278911,1050.777734,848.261378,993.084370,698.701319,1075.209427
max,1936.537991,1608.623599,1936.537991,1635.886550,1765.189198,1723.937301,1059.403185,1633.795368,1716.440393,1230.286798,1376.865626,1189.047924